# =============================================================================
# CLOPUS v3 AI-First Planner
# =============================================================================
"""
AI-first planning system that uses Claude Code intelligence to:
1. Analyze ANY objective (no pattern matching)
2. Generate custom project structures dynamically
3. Create tailored tasks specific to the objective
4. Support multi-project objectives

This replaces the template-based approach with true AI intelligence.
"""

import asyncio
import json
import uuid
from typing import Any, Dict, List, Optional, Tuple
from dataclasses import dataclass, field
import logging

logger = logging.getLogger("clopus.ai_planner")


@dataclass
class AIProject:
    """A project generated by AI analysis."""
    id: str
    name: str
    path: str
    description: str
    technologies: List[str]
    architecture: Dict[str, Any]
    depends_on: List[str] = field(default_factory=list)  # Other project IDs
    shared_artifacts: List[str] = field(default_factory=list)


@dataclass
class AITask:
    """A task generated by AI analysis."""
    id: str
    project_id: str
    title: str
    description: str
    worker_role: str
    priority: int
    dependencies: List[str] = field(default_factory=list)
    expected_artifacts: List[str] = field(default_factory=list)
    validation_criteria: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


class AIPlanner:
    """
    AI-first planning system that uses Claude Code intelligence.

    Key principles:
    - NO hardcoded project types or templates
    - Claude analyzes each objective uniquely
    - Tasks are generated based on specific requirements
    - Multi-project support is native
    """

    # Prompts for AI analysis (injected into worker tasks)
    OBJECTIVE_ANALYSIS_PROMPT = """You are analyzing an objective for CLOPUS, a universal autonomous agent system.

## OBJECTIVE TO ANALYZE:
{objective}

## YOUR TASK:
Analyze this objective and determine:
1. What projects need to be created (can be one or many)
2. What technologies are appropriate
3. The architecture for each project
4. How projects relate to each other (if multiple)

## OUTPUT FORMAT (JSON):
```json
{{
    "analysis": {{
        "summary": "Brief summary of what needs to be built",
        "complexity": "low|medium|high|very_high",
        "estimated_scope": "Description of scope"
    }},
    "projects": [
        {{
            "name": "project-name",
            "description": "What this project does",
            "type": "The type of project (api, webapp, mobile, cli, library, service, etc.)",
            "technologies": ["tech1", "tech2"],
            "architecture": {{
                "framework": "Main framework",
                "database": "Database if needed (or null)",
                "auth": "Auth approach if needed (or null)",
                "cache": "Cache if needed (or null)",
                "key_components": ["component1", "component2"]
            }},
            "depends_on": ["other-project-name if any"],
            "shared_with": ["what this project shares with others"]
        }}
    ],
    "clarifications_needed": ["Questions if any requirements are unclear"],
    "risks": ["Potential risks or challenges"]
}}
```

## IMPORTANT:
- Be specific about technologies - don't be generic
- If the objective is vague, still make your best interpretation
- Support ANY type of project - you're not limited to web/mobile apps
- Consider the full scope: backend, frontend, infrastructure, tooling
- Think about what makes sense for THIS specific objective

Respond ONLY with the JSON output, no other text.
"""

    TASK_GENERATION_PROMPT = """You are generating tasks for a CLOPUS project.

## PROJECT CONTEXT:
Name: {project_name}
Description: {project_description}
Technologies: {technologies}
Architecture: {architecture}

## ORIGINAL OBJECTIVE:
{objective}

## AVAILABLE WORKER ROLES:
- **coder**: Implements features, writes code, creates files
- **tester**: Writes and runs tests (unit, integration, e2e)
- **reviewer**: Reviews code quality, security, best practices
- **researcher**: Investigates APIs, docs, finds solutions
- **debugger**: Fixes bugs, investigates issues
- **designer**: Creates design systems, UI/UX, branding

## YOUR TASK:
Generate a complete list of tasks needed to build this project.

## OUTPUT FORMAT (JSON):
```json
{{
    "tasks": [
        {{
            "title": "Clear, actionable task title",
            "description": "Detailed description of what to do, including:
- Specific files to create
- Patterns to follow
- Requirements to meet",
            "worker_role": "coder|tester|reviewer|researcher|debugger|designer",
            "priority": 1-10,
            "depends_on": ["title of task this depends on"],
            "expected_artifacts": ["file/path/to/create.py", "another/file.tsx"],
            "validation_criteria": ["How to verify this task is complete"]
        }}
    ]
}}
```

## CRITICAL RULES:
1. Tasks must be specific and actionable - not vague
2. Include all necessary setup, implementation, testing, and review tasks
3. Dependencies must form a valid DAG (no cycles)
4. Expected artifacts should be specific file paths
5. Validation criteria should be verifiable
6. Consider the project architecture when generating tasks
7. For APIs with databases: ALWAYS use SQLAlchemy with database sessions, NEVER in-memory dicts
8. Include tasks for documentation, testing, and code review

## EXAMPLE ANTI-PATTERNS (AVOID):
- "Implement the feature" (too vague)
- "Do the backend" (not specific)
- Tasks without expected artifacts
- Circular dependencies

Respond ONLY with the JSON output, no other text.
"""

    def __init__(self, worker_pool, memory_client, config=None):
        """
        Initialize the AI Planner.

        Args:
            worker_pool: WorkerPool instance for dispatching AI tasks
            memory_client: MemoryClient for context retrieval
            config: Optional configuration
        """
        self.worker_pool = worker_pool
        self.memory = memory_client
        self.config = config or {}

        # Cache for ongoing analyses
        self._analysis_cache = {}

        # Session tracking for Claude Code continuity
        # Maps objective_hash -> session_id for continuing related tasks
        self._session_cache = {}

    async def analyze_objective(
        self,
        objective: str,
        context: Optional[Dict] = None,
        objective_key: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Use Claude Code to analyze an objective and determine project structure.

        Args:
            objective: The objective text to analyze
            context: Optional additional context
            objective_key: Key for session continuity (defaults to hash of objective)

        Returns:
            Dict with 'analysis', 'projects', 'clarifications_needed', 'risks'
        """
        logger.info(f"AI analyzing objective: {objective[:100]}...")

        # Generate objective key for session continuity if not provided
        if not objective_key:
            objective_key = f"obj_{hash(objective)}"

        # Build the analysis prompt
        prompt = self.OBJECTIVE_ANALYSIS_PROMPT.format(objective=objective)

        # Add any relevant context from memory
        if self.memory:
            try:
                relevant_context = await self.memory.get_relevant_context(objective)
                if relevant_context:
                    prompt += f"\n\n## RELEVANT PAST CONTEXT:\n{relevant_context}"
            except Exception as e:
                logger.warning(f"Could not get memory context: {e}")

        # Dispatch to researcher worker for analysis with session tracking
        result = await self._dispatch_ai_task(
            task_type="OBJECTIVE_ANALYSIS",
            prompt=prompt,
            worker_role="researcher",
            objective_key=objective_key  # Track session for follow-up tasks
        )

        if not result:
            logger.error("AI analysis failed, returning fallback structure")
            return self._fallback_analysis(objective)

        # Parse the JSON response
        try:
            analysis = self._parse_json_response(result)
            logger.info(f"AI analysis complete: {len(analysis.get('projects', []))} projects identified")

            # Cache the analysis
            cache_key = hash(objective)
            self._analysis_cache[cache_key] = analysis

            return analysis
        except Exception as e:
            logger.error(f"Failed to parse AI analysis: {e}")
            return self._fallback_analysis(objective)

    async def generate_tasks(
        self,
        project: Dict[str, Any],
        objective: str,
        all_projects: Optional[List[Dict]] = None,
        objective_key: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """
        Use Claude Code to generate tasks for a specific project.

        Args:
            project: Project definition from analyze_objective
            objective: Original objective text
            all_projects: All projects (for dependency context)
            objective_key: Key for session continuity (to continue from analysis)

        Returns:
            List of task dictionaries
        """
        project_name = project.get("name", "project")
        logger.info(f"AI generating tasks for project: {project_name}")

        # Use same objective key for session continuity with analysis
        if not objective_key:
            objective_key = f"obj_{hash(objective)}"

        # Build the task generation prompt
        prompt = self.TASK_GENERATION_PROMPT.format(
            project_name=project_name,
            project_description=project.get("description", ""),
            technologies=", ".join(project.get("technologies", [])),
            architecture=json.dumps(project.get("architecture", {}), indent=2),
            objective=objective
        )

        # Add multi-project context if applicable
        if all_projects and len(all_projects) > 1:
            other_projects = [p for p in all_projects if p.get("name") != project_name]
            prompt += f"\n\n## OTHER PROJECTS IN THIS OBJECTIVE:\n"
            for p in other_projects:
                prompt += f"- {p.get('name')}: {p.get('description', '')}\n"
            prompt += "\nConsider integration and shared components between projects.\n"

        # Dispatch to researcher for task generation with session continuity
        result = await self._dispatch_ai_task(
            task_type="TASK_GENERATION",
            prompt=prompt,
            worker_role="researcher",
            objective_key=objective_key  # Continue from analysis session
        )

        if not result:
            logger.error(f"AI task generation failed for {project_name}")
            return self._fallback_tasks(project)

        # Parse the JSON response
        try:
            task_data = self._parse_json_response(result)
            tasks = task_data.get("tasks", [])

            # Process and validate tasks
            processed_tasks = self._process_tasks(tasks, project_name)
            logger.info(f"Generated {len(processed_tasks)} tasks for {project_name}")

            return processed_tasks
        except Exception as e:
            logger.error(f"Failed to parse AI tasks: {e}")
            return self._fallback_tasks(project)

    async def plan_objective(
        self,
        objective: str,
        objective_id: str
    ) -> Tuple[List[AIProject], List[AITask]]:
        """
        Full AI-powered planning: analyze objective and generate all tasks.

        Uses Claude Code session continuity to maintain context across:
        1. Objective analysis
        2. Task generation for each project

        Args:
            objective: The user's objective text
            objective_id: ID for tracking

        Returns:
            Tuple of (projects, tasks)
        """
        logger.info(f"AI planning objective: {objective_id}")

        # Use objective_id as the session key for continuity
        objective_key = f"plan_{objective_id}"

        # Step 1: Analyze the objective (starts the session)
        analysis = await self.analyze_objective(
            objective,
            objective_key=objective_key
        )

        # Check if clarifications are needed
        clarifications = analysis.get("clarifications_needed", [])
        if clarifications:
            logger.warning(f"Clarifications might help: {clarifications}")
            # Could trigger question system here if confidence is low

        # Step 2: Create project objects
        projects = []
        project_configs = analysis.get("projects", [])

        for proj_config in project_configs:
            project = AIProject(
                id=str(uuid.uuid4()),
                name=proj_config.get("name", "project"),
                path=f"/workspace/{proj_config.get('name', 'project')}",
                description=proj_config.get("description", ""),
                technologies=proj_config.get("technologies", []),
                architecture=proj_config.get("architecture", {}),
                depends_on=proj_config.get("depends_on", []),
                shared_artifacts=proj_config.get("shared_with", [])
            )
            projects.append(project)

        # Step 3: Generate tasks for each project (continues the session)
        all_tasks = []
        for project in projects:
            project_config = next(
                (p for p in project_configs if p.get("name") == project.name),
                {}
            )
            # Use same objective_key to continue the session from analysis
            task_dicts = await self.generate_tasks(
                project_config,
                objective,
                all_projects=project_configs,
                objective_key=objective_key  # Session continuity
            )

            for task_dict in task_dicts:
                task = AITask(
                    id=str(uuid.uuid4()),
                    project_id=project.id,
                    title=task_dict.get("title", ""),
                    description=task_dict.get("description", ""),
                    worker_role=task_dict.get("worker_role", "coder"),
                    priority=task_dict.get("priority", 5),
                    dependencies=task_dict.get("dependencies", []),
                    expected_artifacts=task_dict.get("expected_artifacts", []),
                    validation_criteria=task_dict.get("validation_criteria", []),
                    metadata={
                        "project_name": project.name,
                        "project_path": project.path,
                        **task_dict.get("metadata", {})
                    }
                )
                all_tasks.append(task)

        # Step 4: Resolve task dependencies (convert title references to IDs)
        all_tasks = self._resolve_task_dependencies(all_tasks)

        logger.info(f"AI planning complete: {len(projects)} projects, {len(all_tasks)} tasks")
        return projects, all_tasks

    async def _dispatch_ai_task(
        self,
        task_type: str,
        prompt: str,
        worker_role: str = "researcher",
        objective_key: Optional[str] = None
    ) -> Optional[str]:
        """
        Dispatch a task to a worker for AI processing with session continuity.

        Args:
            task_type: Type of AI task (OBJECTIVE_ANALYSIS, TASK_GENERATION)
            prompt: The prompt to send to Claude
            worker_role: Worker role to use
            objective_key: Key to track session continuity across related tasks

        Returns:
            The result string from Claude, or None if failed
        """
        if not self.worker_pool:
            logger.error("No worker pool available for AI dispatch")
            return None

        try:
            # Determine session mode for continuity
            session_mode = "auto"
            resume_session = None

            if objective_key:
                # Check if we have an existing session for this objective
                cached_session = self._session_cache.get(objective_key)
                if cached_session:
                    # Continue the existing session for related tasks
                    session_mode = "continue"
                    logger.debug(f"Continuing session for objective: {objective_key}")

            # Use the verification task dispatch which doesn't go through memory
            result = await self.worker_pool.dispatch_verification_task(
                task_type,
                {
                    "prompt": prompt,
                    "expect_json": True
                },
                timeout_seconds=120,  # AI planning needs more time
                session_mode=session_mode,
                resume_session=resume_session
            )

            if result:
                # Cache the session ID for future continuity
                session_id = result.get("_session_id") if isinstance(result, dict) else None
                if session_id and objective_key:
                    self._session_cache[objective_key] = session_id
                    logger.debug(f"Cached session {session_id} for objective {objective_key}")

                # Extract the actual result
                if isinstance(result, dict):
                    if "result" in result:
                        return result["result"]
                    elif "error" not in result:
                        # Remove internal session tracking field
                        result.pop("_session_id", None)
                        return str(result)
                else:
                    return str(result)

            return None

        except Exception as e:
            logger.error(f"Error dispatching AI task: {e}")
            return None

    def _parse_json_response(self, response: str) -> Dict:
        """Parse JSON from AI response, handling markdown code blocks."""
        text = response.strip()

        # Remove markdown code blocks if present
        if text.startswith("```json"):
            text = text[7:]
        elif text.startswith("```"):
            text = text[3:]

        if text.endswith("```"):
            text = text[:-3]

        text = text.strip()
        return json.loads(text)

    def _process_tasks(
        self,
        tasks: List[Dict],
        project_name: str
    ) -> List[Dict]:
        """Process and validate tasks from AI generation."""
        processed = []

        for task in tasks:
            # Ensure required fields
            if not task.get("title"):
                continue

            # Validate worker role
            valid_roles = {"coder", "tester", "reviewer", "researcher", "debugger", "designer"}
            role = task.get("worker_role", "coder").lower()
            if role not in valid_roles:
                role = "coder"

            # Normalize priority
            priority = task.get("priority", 5)
            if not isinstance(priority, int):
                priority = 5
            priority = max(1, min(10, priority))

            processed.append({
                "title": task["title"],
                "description": task.get("description", task["title"]),
                "worker_role": role,
                "priority": priority,
                "depends_on": task.get("depends_on", []),
                "expected_artifacts": task.get("expected_artifacts", []),
                "validation_criteria": task.get("validation_criteria", []),
                "metadata": {
                    "project_name": project_name,
                    "ai_generated": True
                }
            })

        return processed

    def _resolve_task_dependencies(self, tasks: List[AITask]) -> List[AITask]:
        """Convert title-based dependencies to ID-based."""
        # Build title -> ID map
        title_to_id = {task.title.lower(): task.id for task in tasks}

        for task in tasks:
            resolved_deps = []
            for dep in task.dependencies:
                dep_lower = dep.lower()
                if dep_lower in title_to_id:
                    resolved_deps.append(title_to_id[dep_lower])
                else:
                    # Try partial match
                    for title, task_id in title_to_id.items():
                        if dep_lower in title or title in dep_lower:
                            resolved_deps.append(task_id)
                            break
            task.dependencies = resolved_deps

        return tasks

    def _fallback_analysis(self, objective: str) -> Dict[str, Any]:
        """Fallback when AI analysis fails."""
        logger.warning("Using fallback analysis")
        return {
            "analysis": {
                "summary": objective[:200],
                "complexity": "medium",
                "estimated_scope": "Standard project"
            },
            "projects": [{
                "name": "project",
                "description": objective,
                "type": "custom",
                "technologies": [],
                "architecture": {
                    "framework": "to-be-determined",
                    "key_components": []
                },
                "depends_on": [],
                "shared_with": []
            }],
            "clarifications_needed": [
                "AI analysis unavailable - proceeding with minimal structure"
            ],
            "risks": ["May need manual task adjustments"]
        }

    def _fallback_tasks(self, project: Dict) -> List[Dict]:
        """Fallback task list when AI generation fails."""
        logger.warning(f"Using fallback tasks for {project.get('name')}")
        project_name = project.get("name", "project")
        return [
            {
                "title": "Research and planning",
                "description": f"Analyze requirements and plan implementation for {project_name}",
                "worker_role": "researcher",
                "priority": 10,
                "depends_on": [],
                "expected_artifacts": [],
                "validation_criteria": ["Research document exists"]
            },
            {
                "title": "Project setup",
                "description": f"Initialize {project_name} with required dependencies",
                "worker_role": "coder",
                "priority": 9,
                "depends_on": ["Research and planning"],
                "expected_artifacts": ["package.json or requirements.txt"],
                "validation_criteria": ["Project can be built"]
            },
            {
                "title": "Core implementation",
                "description": f"Implement main functionality for {project_name}",
                "worker_role": "coder",
                "priority": 8,
                "depends_on": ["Project setup"],
                "expected_artifacts": [],
                "validation_criteria": ["Core features work"]
            },
            {
                "title": "Testing",
                "description": "Write and run tests",
                "worker_role": "tester",
                "priority": 5,
                "depends_on": ["Core implementation"],
                "expected_artifacts": ["test files"],
                "validation_criteria": ["Tests pass"]
            },
            {
                "title": "Code review",
                "description": "Review code quality and best practices",
                "worker_role": "reviewer",
                "priority": 3,
                "depends_on": ["Core implementation"],
                "expected_artifacts": [],
                "validation_criteria": ["Review complete"]
            }
        ]


def convert_ai_tasks_to_planned_tasks(
    ai_tasks: List[AITask],
    projects: List[AIProject]
) -> List[Dict]:
    """
    Convert AITask objects to the dictionary format expected by the rest of the system.
    """
    # Build project ID to path map
    project_paths = {p.id: p.path for p in projects}
    project_names = {p.id: p.name for p in projects}

    result = []
    for task in ai_tasks:
        project_path = project_paths.get(task.project_id, "/workspace/project")
        project_name = project_names.get(task.project_id, "project")

        # Build comprehensive description with project context
        description = task.description
        description += f"\n\nProject Path: {project_path}"

        if task.expected_artifacts:
            description += "\n\n## Expected Artifacts:"
            for artifact in task.expected_artifacts:
                description += f"\n- {artifact}"

        if task.validation_criteria:
            description += "\n\n## Validation Criteria:"
            for criterion in task.validation_criteria:
                description += f"\n- {criterion}"

        result.append({
            "id": task.id,
            "title": task.title,
            "description": description,
            "worker_role": task.worker_role,
            "priority": task.priority,
            "dependencies": task.dependencies,
            "estimated_duration": "medium",
            "validation_required": True,
            "metadata": {
                **task.metadata,
                "project_id": task.project_id,
                "project_path": project_path,
                "project_name": project_name,
                "expected_artifacts": task.expected_artifacts,
                "validation_criteria": task.validation_criteria,
                "ai_generated": True
            }
        })

    return result


async def create_ai_planner(worker_pool, memory_client, config=None) -> AIPlanner:
    """Factory function to create an AI Planner."""
    return AIPlanner(worker_pool, memory_client, config)
