# =============================================================================
# CLOPUS v3 Knowledge Base
# =============================================================================
"""
Manages shared knowledge: patterns, solutions, and mistakes.
Part of the self-generating ecosystem.
"""

import asyncio
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger("clopus.knowledge_base")


class KnowledgeBase:
    """Manages patterns, solutions, and mistakes for learning."""

    def __init__(
        self,
        memory_client,
        knowledge_path: str = "/app/knowledge"
    ):
        self.memory = memory_client
        self.base_path = Path(knowledge_path)
        self.patterns_path = self.base_path / "patterns"
        self.solutions_path = self.base_path / "solutions"
        self.mistakes_path = self.base_path / "mistakes"

        # Ensure directories exist
        for path in [self.patterns_path, self.solutions_path, self.mistakes_path]:
            path.mkdir(parents=True, exist_ok=True)

    # =========================================================================
    # PATTERNS - Reusable code/workflow patterns
    # =========================================================================

    async def store_pattern(
        self,
        name: str,
        category: str,
        description: str,
        pattern_content: str,
        tags: Optional[List[str]] = None,
        source_task: Optional[str] = None
    ) -> Path:
        """Store a reusable pattern."""
        pattern_dir = self.patterns_path / category
        pattern_dir.mkdir(parents=True, exist_ok=True)

        pattern_file = pattern_dir / f"{name}.md"

        content = f"""# {name}

> Category: {category}
> Tags: {', '.join(tags or [])}
> Created: {datetime.now().isoformat()}
> Source: {source_task or 'manual'}

## Description

{description}

## Pattern

{pattern_content}

---
*Auto-generated by CLOPUS Knowledge Base*
"""

        pattern_file.write_text(content)

        # Store in long-term memory for semantic search
        await self.memory.long_term.store(
            memory_type="pattern",
            content=f"Pattern: {name} - {description}",
            metadata={
                "name": name,
                "category": category,
                "tags": tags or [],
                "path": str(pattern_file)
            }
        )

        logger.info(f"Stored pattern: {name} in {category}")
        return pattern_file

    async def find_patterns(
        self,
        query: str,
        category: Optional[str] = None,
        limit: int = 5
    ) -> List[Dict]:
        """Find patterns matching a query."""
        # Search in long-term memory
        results = await self.memory.long_term.search(
            query=f"pattern {query}",
            n_results=limit * 2
        )

        patterns = []
        for result in results:
            if result.metadata.get("type") == "pattern":
                if category and result.metadata.get("category") != category:
                    continue

                pattern_path = Path(result.metadata.get("path", ""))
                if pattern_path.exists():
                    patterns.append({
                        "name": result.metadata.get("name"),
                        "category": result.metadata.get("category"),
                        "path": str(pattern_path),
                        "content": pattern_path.read_text()[:1000],
                        "relevance": result.relevance_score
                    })

                if len(patterns) >= limit:
                    break

        return patterns

    # =========================================================================
    # SOLUTIONS - Common problem solutions
    # =========================================================================

    async def store_solution(
        self,
        problem: str,
        solution: str,
        category: str,
        tags: Optional[List[str]] = None,
        source_task: Optional[str] = None
    ) -> Path:
        """Store a problem-solution pair."""
        solution_dir = self.solutions_path / category
        solution_dir.mkdir(parents=True, exist_ok=True)

        # Generate filename from problem
        safe_name = "".join(c if c.isalnum() else "-" for c in problem[:50]).strip("-")
        solution_file = solution_dir / f"{safe_name}.md"

        content = f"""# Solution: {problem[:100]}

> Category: {category}
> Tags: {', '.join(tags or [])}
> Created: {datetime.now().isoformat()}
> Source: {source_task or 'manual'}

## Problem

{problem}

## Solution

{solution}

---
*Auto-generated by CLOPUS Knowledge Base*
"""

        solution_file.write_text(content)

        # Store in long-term memory
        await self.memory.long_term.store(
            memory_type="solution",
            content=f"Problem: {problem}\nSolution: {solution[:500]}",
            metadata={
                "problem": problem[:200],
                "category": category,
                "tags": tags or [],
                "path": str(solution_file)
            }
        )

        logger.info(f"Stored solution for: {problem[:50]}...")
        return solution_file

    async def find_solutions(
        self,
        problem_query: str,
        limit: int = 3
    ) -> List[Dict]:
        """Find solutions for a problem."""
        results = await self.memory.long_term.search(
            query=f"solution problem {problem_query}",
            n_results=limit * 2
        )

        solutions = []
        for result in results:
            if result.metadata.get("type") == "solution":
                solution_path = Path(result.metadata.get("path", ""))
                if solution_path.exists():
                    solutions.append({
                        "problem": result.metadata.get("problem"),
                        "path": str(solution_path),
                        "content": solution_path.read_text(),
                        "relevance": result.relevance_score
                    })

                if len(solutions) >= limit:
                    break

        return solutions

    # =========================================================================
    # MISTAKES - Anti-patterns to avoid
    # =========================================================================

    async def store_mistake(
        self,
        mistake: str,
        what_went_wrong: str,
        how_to_avoid: str,
        category: str,
        severity: str = "medium",  # low, medium, high, critical
        source_task: Optional[str] = None
    ) -> Path:
        """Store a mistake/anti-pattern to avoid."""
        mistake_dir = self.mistakes_path / category
        mistake_dir.mkdir(parents=True, exist_ok=True)

        # Generate filename
        safe_name = "".join(c if c.isalnum() else "-" for c in mistake[:50]).strip("-")
        mistake_file = mistake_dir / f"{safe_name}.md"

        content = f"""# Mistake: {mistake[:100]}

> Category: {category}
> Severity: {severity}
> Created: {datetime.now().isoformat()}
> Source: {source_task or 'learned from failure'}

## What Happened

{what_went_wrong}

## How to Avoid

{how_to_avoid}

## Severity: {severity.upper()}

{"⚠️ " * (["low", "medium", "high", "critical"].index(severity) + 1)}

---
*Auto-generated by CLOPUS Knowledge Base*
"""

        mistake_file.write_text(content)

        # Store in long-term memory
        await self.memory.long_term.store(
            memory_type="mistake",
            content=f"Mistake: {mistake}\nAvoid: {how_to_avoid[:500]}",
            metadata={
                "mistake": mistake[:200],
                "category": category,
                "severity": severity,
                "path": str(mistake_file)
            }
        )

        logger.info(f"Stored mistake to avoid: {mistake[:50]}...")
        return mistake_file

    async def check_for_mistakes(
        self,
        context: str,
        limit: int = 3
    ) -> List[Dict]:
        """Check if context matches any known mistakes."""
        results = await self.memory.long_term.search(
            query=f"mistake avoid {context}",
            n_results=limit * 2
        )

        mistakes = []
        for result in results:
            if result.metadata.get("type") == "mistake":
                mistake_path = Path(result.metadata.get("path", ""))
                if mistake_path.exists():
                    mistakes.append({
                        "mistake": result.metadata.get("mistake"),
                        "severity": result.metadata.get("severity"),
                        "path": str(mistake_path),
                        "content": mistake_path.read_text(),
                        "relevance": result.relevance_score
                    })

                if len(mistakes) >= limit:
                    break

        return mistakes

    # =========================================================================
    # AUTO-LEARNING FROM TASK OUTCOMES
    # =========================================================================

    async def learn_from_task_failure(
        self,
        task_title: str,
        task_description: str,
        error: str,
        validation_failures: Optional[List[str]] = None
    ) -> None:
        """Learn from a task failure - store as mistake."""
        category = "task-failures"

        # Determine severity based on validation failures
        severity = "medium"
        if validation_failures:
            if "security" in str(validation_failures).lower():
                severity = "critical"
            elif len(validation_failures) > 3:
                severity = "high"

        await self.store_mistake(
            mistake=f"Task failed: {task_title}",
            what_went_wrong=f"Error: {error}\n\nTask: {task_description[:500]}",
            how_to_avoid=f"Validation failures: {validation_failures}\n\nEnsure proper validation before completing similar tasks.",
            category=category,
            severity=severity,
            source_task=task_title
        )

    async def learn_from_task_success(
        self,
        task_title: str,
        task_description: str,
        approach: str
    ) -> None:
        """Learn from a task success - store as solution if novel."""
        # Check if similar solution already exists
        existing = await self.find_solutions(task_title, limit=1)
        if existing and existing[0].get("relevance", 0) > 0.9:
            return  # Already have this solution

        await self.store_solution(
            problem=task_title,
            solution=approach,
            category="task-solutions",
            source_task=task_title
        )

    # =========================================================================
    # STATISTICS
    # =========================================================================

    async def get_statistics(self) -> Dict:
        """Get knowledge base statistics."""
        def count_files(path: Path) -> int:
            return sum(1 for _ in path.rglob("*.md"))

        return {
            "patterns": count_files(self.patterns_path),
            "solutions": count_files(self.solutions_path),
            "mistakes": count_files(self.mistakes_path),
            "total": (
                count_files(self.patterns_path) +
                count_files(self.solutions_path) +
                count_files(self.mistakes_path)
            )
        }
