# =============================================================================
# CLOPUS v3 Project Setup
# =============================================================================
"""
Handles project initialization including CLAUDE.md generation.

NEW IN v3.2: AI-First Project Detection
- Uses Claude intelligence for semantic project type detection
- Falls back to keyword matching when AI unavailable
"""

import asyncio
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional, TYPE_CHECKING
import logging

if TYPE_CHECKING:
    from .ai_first import AIFirstEngine

logger = logging.getLogger("clopus.project_setup")


CLAUDE_MD_TEMPLATE = '''# CLAUDE.md - Project Guidelines

> This file provides project-specific context for Claude Code workers.
> Generated by CLOPUS v3 on {created_at}

## Project: {project_name}

{description}

## Build & Test Commands

```bash
# Install dependencies
{install_cmd}

# Run development server
{dev_cmd}

# Run tests
{test_cmd}

# Build for production
{build_cmd}

# Lint code
{lint_cmd}
```

## Project Structure

{structure}

## Code Standards

- Follow existing code patterns and conventions
- All code must pass the 8-stage validation pipeline:
  1. Syntax checking
  2. Linting (ESLint/Pylint)
  3. Build verification
  4. Unit tests
  5. Integration tests
  6. E2E tests (Playwright)
  7. Security scanning
  8. Code review

## MANDATORY REQUIREMENTS

1. **All code must pass validation** - Tasks fail if validation fails
2. **No hardcoded secrets** - Use environment variables
3. **Error handling is required** - Never swallow errors silently
4. **Tests are required** - New features need test coverage
5. **Documentation updates** - Update docs when changing behavior

## Technology Stack

{tech_stack}

## Environment Variables

{env_vars}

## Important Files

{important_files}

## Notes

{notes}

---
*This file is auto-generated by CLOPUS. Edit to customize project guidelines.*
'''


class ProjectSetup:
    """
    Handles project initialization and CLAUDE.md generation.

    NEW IN v3.2: AI-First Project Detection
    - Uses AI intelligence for semantic project type detection
    - Falls back to keyword matching when AI unavailable
    """

    def __init__(self, workspace_path: str = "/workspace"):
        self.workspace = Path(workspace_path)

        # AI-First Engine (set by orchestrator, NEW in v3.2)
        self.ai_engine: Optional["AIFirstEngine"] = None

    def set_ai_engine(self, ai_engine: "AIFirstEngine") -> None:
        """Set the AI-first engine for intelligent project detection."""
        self.ai_engine = ai_engine
        logger.info("AI-First Engine connected to project setup")

    async def setup_project(
        self,
        project_path: str,
        objective_content: str,
        project_type: Optional[str] = None
    ) -> Path:
        """Set up a new project with CLAUDE.md."""
        path = Path(project_path)
        path.mkdir(parents=True, exist_ok=True)

        # Detect or use provided project type
        if not project_type:
            project_type = await self._detect_project_type(path, objective_content)

        # Generate CLAUDE.md
        claude_md = await self._generate_claude_md(path, objective_content, project_type)
        claude_md_path = path / "CLAUDE.md"
        claude_md_path.write_text(claude_md)

        logger.info(f"Created CLAUDE.md for project: {path}")
        return claude_md_path

    async def _detect_project_type(self, path: Path, objective: str) -> str:
        """
        Detect project type from existing files or objective.

        NEW IN v3.2: AI-First approach
        Priority:
        1. AI-First Engine (semantic understanding)
        2. Keyword matching (deprecated fallback)
        """
        # Try AI-First Engine for semantic understanding
        if self.ai_engine:
            try:
                # Gather file context
                existing_files = []
                for pattern in ["*.json", "*.txt", "*.toml", "*.yaml", "*.yml", "*.md"]:
                    existing_files.extend([f.name for f in path.glob(pattern)])

                result = await self.ai_engine.analyze_project_requirements(
                    objective=objective,
                    existing_files=existing_files,
                    context={"path": str(path)}
                )

                if result.success and result.result:
                    detected_type = result.result.get("project_type")
                    if detected_type:
                        logger.debug(f"AI-first detected project type: {detected_type}")
                        return detected_type
            except Exception as e:
                logger.debug(f"AI-first project detection failed: {e}")

        # Fallback to keyword matching (deprecated)
        return self._keyword_detect_project_type(path, objective)

    def _keyword_detect_project_type(self, path: Path, objective: str) -> str:
        """DEPRECATED: Keyword-based project type detection. Use AI-first instead."""
        objective_lower = objective.lower()

        # Check objective keywords
        if any(kw in objective_lower for kw in ["react", "tsx", "vite", "next"]):
            return "react-typescript"
        if any(kw in objective_lower for kw in ["python", "fastapi", "flask", "django"]):
            return "python"
        if any(kw in objective_lower for kw in ["node", "express", "nest"]):
            return "nodejs"
        if any(kw in objective_lower for kw in ["html5", "html", "vanilla"]):
            return "html5"
        if any(kw in objective_lower for kw in ["go", "golang"]):
            return "golang"
        if any(kw in objective_lower for kw in ["rust", "cargo"]):
            return "rust"

        # Check existing files
        if (path / "package.json").exists():
            pkg = (path / "package.json").read_text()
            if "react" in pkg or "tsx" in pkg:
                return "react-typescript"
            return "nodejs"
        if (path / "requirements.txt").exists() or (path / "pyproject.toml").exists():
            return "python"
        if (path / "go.mod").exists():
            return "golang"
        if (path / "Cargo.toml").exists():
            return "rust"

        return "unknown"

    async def _generate_claude_md(
        self,
        path: Path,
        objective: str,
        project_type: str
    ) -> str:
        """Generate CLAUDE.md content based on project type."""
        config = self._get_project_config(project_type)
        project_name = path.name

        # Get project structure if it exists
        structure = self._get_project_structure(path)

        return CLAUDE_MD_TEMPLATE.format(
            created_at=datetime.now().isoformat(),
            project_name=project_name,
            description=objective[:500] if objective else "No description provided.",
            install_cmd=config.get("install_cmd", "npm install"),
            dev_cmd=config.get("dev_cmd", "npm run dev"),
            test_cmd=config.get("test_cmd", "npm test"),
            build_cmd=config.get("build_cmd", "npm run build"),
            lint_cmd=config.get("lint_cmd", "npm run lint"),
            structure=structure or "Project structure will be generated.",
            tech_stack=config.get("tech_stack", "To be determined based on implementation."),
            env_vars=config.get("env_vars", "No environment variables defined yet."),
            important_files=config.get("important_files", "- CLAUDE.md (this file)"),
            notes=config.get("notes", "No additional notes.")
        )

    def _get_project_config(self, project_type: str) -> Dict:
        """Get configuration for different project types."""
        configs = {
            "react-typescript": {
                "install_cmd": "npm install",
                "dev_cmd": "npm run dev",
                "test_cmd": "npm test",
                "build_cmd": "npm run build",
                "lint_cmd": "npm run lint",
                "tech_stack": "- React 18+\n- TypeScript 5+\n- Vite\n- ESLint\n- Vitest",
                "important_files": "- src/App.tsx\n- src/main.tsx\n- vite.config.ts\n- tsconfig.json",
                "notes": "Use functional components with hooks. Prefer TypeScript strict mode."
            },
            "python": {
                "install_cmd": "pip install -r requirements.txt",
                "dev_cmd": "python -m uvicorn main:app --reload",
                "test_cmd": "pytest",
                "build_cmd": "python -m build",
                "lint_cmd": "ruff check . && mypy .",
                "tech_stack": "- Python 3.11+\n- FastAPI/Flask\n- Pydantic\n- pytest\n- Ruff/Mypy",
                "important_files": "- main.py\n- requirements.txt\n- pyproject.toml",
                "notes": "Use type hints. Follow PEP 8. Use async where beneficial."
            },
            "nodejs": {
                "install_cmd": "npm install",
                "dev_cmd": "npm run dev",
                "test_cmd": "npm test",
                "build_cmd": "npm run build",
                "lint_cmd": "npm run lint",
                "tech_stack": "- Node.js 20+\n- TypeScript\n- ESLint\n- Jest/Vitest",
                "important_files": "- src/index.ts\n- package.json\n- tsconfig.json",
                "notes": "Use async/await. Handle errors properly."
            },
            "html5": {
                "install_cmd": "# No dependencies - pure HTML5",
                "dev_cmd": "python -m http.server 8080",
                "test_cmd": "# Manual testing or Playwright E2E",
                "build_cmd": "# No build step - serve directly",
                "lint_cmd": "# Validate HTML with W3C validator",
                "tech_stack": "- HTML5\n- CSS3\n- Vanilla JavaScript\n- No external dependencies",
                "important_files": "- index.html\n- styles.css\n- script.js",
                "notes": "Pure HTML5/CSS3/JS. No frameworks. Must work offline."
            },
            "golang": {
                "install_cmd": "go mod download",
                "dev_cmd": "go run .",
                "test_cmd": "go test ./...",
                "build_cmd": "go build -o bin/app",
                "lint_cmd": "golangci-lint run",
                "tech_stack": "- Go 1.21+\n- Standard library\n- golangci-lint",
                "important_files": "- main.go\n- go.mod\n- go.sum",
                "notes": "Follow Go idioms. Use gofmt."
            },
            "rust": {
                "install_cmd": "cargo build",
                "dev_cmd": "cargo run",
                "test_cmd": "cargo test",
                "build_cmd": "cargo build --release",
                "lint_cmd": "cargo clippy",
                "tech_stack": "- Rust stable\n- Cargo\n- Clippy",
                "important_files": "- src/main.rs\n- Cargo.toml",
                "notes": "Handle all Results. Use clippy suggestions."
            },
            "unknown": {
                "install_cmd": "# Determine based on project",
                "dev_cmd": "# Determine based on project",
                "test_cmd": "# Determine based on project",
                "build_cmd": "# Determine based on project",
                "lint_cmd": "# Determine based on project",
                "tech_stack": "To be determined.",
                "important_files": "- CLAUDE.md (this file)",
                "notes": "Determine project type and update this file."
            }
        }
        return configs.get(project_type, configs["unknown"])

    def _get_project_structure(self, path: Path, max_depth: int = 3) -> str:
        """Get directory structure as a tree string."""
        if not path.exists():
            return ""

        lines = []
        self._build_tree(path, lines, "", max_depth, 0)
        return "\n".join(lines[:50])  # Limit to 50 lines

    def _build_tree(
        self,
        path: Path,
        lines: list,
        prefix: str,
        max_depth: int,
        current_depth: int
    ):
        """Build tree structure recursively."""
        if current_depth >= max_depth:
            return

        # Skip common directories
        skip_dirs = {
            "node_modules", "__pycache__", ".git", "dist", "build",
            ".next", "venv", ".venv", "target", ".cargo"
        }

        try:
            entries = sorted(path.iterdir(), key=lambda x: (not x.is_dir(), x.name))
            entries = [e for e in entries if e.name not in skip_dirs]

            for i, entry in enumerate(entries[:20]):  # Limit entries
                is_last = i == len(entries) - 1
                connector = "└── " if is_last else "├── "
                lines.append(f"{prefix}{connector}{entry.name}")

                if entry.is_dir():
                    extension = "    " if is_last else "│   "
                    self._build_tree(
                        entry, lines, prefix + extension,
                        max_depth, current_depth + 1
                    )
        except PermissionError:
            pass
